"""seed_basic_rules

Revision ID: 453fcecaacf4
Revises: a621a1d03594
Create Date: 2025-09-20 00:49:52.720693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '453fcecaacf4'
down_revision = 'a621a1d03594'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Seed basic rules as specified in PRP
    op.execute(text("""
        INSERT INTO rules (name, intent, constraints, priority, is_active, created_at) VALUES
        ('yoga_basic', 'recommend_outfits', '{"activity": "yoga", "category": ["activewear", "loungewear"], "material": ["cotton", "spandex", "polyester"], "comfort": "high", "stretch": true}', 5, true, datetime('now')),
        ('dinner_budget_50', 'recommend_outfits', '{"occasion": "dinner", "budget_max": 50, "formality": "elevated casual", "weekend": true}', 7, true, datetime('now')),
        ('slimming_rules', 'recommend_outfits', '{"objectives": ["slimming"], "palette": ["dark", "monochrome"], "silhouette": ["structured", "vertical lines"], "rise": ["mid", "high"]}', 8, true, datetime('now'))
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove seeded rules
    op.execute(text("DELETE FROM rules WHERE name IN ('yoga_basic', 'dinner_budget_50', 'slimming_rules')"))
    # ### end Alembic commands ###