"""add_missing_indexes_and_seed_rules

Revision ID: a621a1d03594
Revises: 9fe176c77da3
Create Date: 2025-09-20 00:45:37.775619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'a621a1d03594'
down_revision = '9fe176c77da3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_items_attributes_category', 'items', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index('idx_items_attributes_color', 'items', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index('idx_items_created_at', 'items', ['created_at'], unique=False)
    op.create_index('idx_items_in_stock', 'items', ['in_stock'], unique=False)
    op.create_index('idx_items_price', 'items', ['price'], unique=False)
    op.create_index('idx_outfit_items_item_id', 'outfit_items', ['item_id'], unique=False)
    op.create_index('idx_outfit_items_outfit_id', 'outfit_items', ['outfit_id'], unique=False)
    op.create_index('idx_outfit_items_role', 'outfit_items', ['role'], unique=False)
    op.create_index('idx_outfits_created_at', 'outfits', ['created_at'], unique=False)
    op.create_index('idx_outfits_intent_tags', 'outfits', ['intent_tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_outfits_score', 'outfits', ['score'], unique=False)
    op.create_index('idx_rules_constraints', 'rules', ['constraints'], unique=False, postgresql_using='gin')
    op.create_index('idx_rules_intent', 'rules', ['intent'], unique=False)
    op.create_index('idx_rules_is_active', 'rules', ['is_active'], unique=False)
    op.create_index('idx_rules_name', 'rules', ['name'], unique=False)
    op.create_index('idx_rules_priority', 'rules', ['priority'], unique=False)
    # ### end Alembic commands ###

    # Seed basic rules as specified in PRP
    op.execute(text("""
        INSERT INTO rules (name, intent, constraints, priority, is_active, created_at) VALUES
        ('yoga_basic', 'recommend_outfits', '{"activity": "yoga", "category": ["activewear", "loungewear"], "material": ["cotton", "spandex", "polyester"], "comfort": "high", "stretch": true}', 5, true, datetime('now')),
        ('dinner_budget_50', 'recommend_outfits', '{"occasion": "dinner", "budget_max": 50, "formality": "elevated casual", "weekend": true}', 7, true, datetime('now')),
        ('slimming_rules', 'recommend_outfits', '{"objectives": ["slimming"], "palette": ["dark", "monochrome"], "silhouette": ["structured", "vertical lines"], "rise": ["mid", "high"]}', 8, true, datetime('now'))
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rules_priority', table_name='rules')
    op.drop_index('idx_rules_name', table_name='rules')
    op.drop_index('idx_rules_is_active', table_name='rules')
    op.drop_index('idx_rules_intent', table_name='rules')
    op.drop_index('idx_rules_constraints', table_name='rules', postgresql_using='gin')
    op.drop_index('idx_outfits_score', table_name='outfits')
    op.drop_index('idx_outfits_intent_tags', table_name='outfits', postgresql_using='gin')
    op.drop_index('idx_outfits_created_at', table_name='outfits')
    op.drop_index('idx_outfit_items_role', table_name='outfit_items')
    op.drop_index('idx_outfit_items_outfit_id', table_name='outfit_items')
    op.drop_index('idx_outfit_items_item_id', table_name='outfit_items')
    op.drop_index('idx_items_price', table_name='items')
    op.drop_index('idx_items_in_stock', table_name='items')
    op.drop_index('idx_items_created_at', table_name='items')
    op.drop_index('idx_items_attributes_color', table_name='items', postgresql_using='gin')
    op.drop_index('idx_items_attributes_category', table_name='items', postgresql_using='gin')
    # ### end Alembic commands ###

    # Remove seeded rules
    op.execute(text("DELETE FROM rules WHERE name IN ('yoga_basic', 'dinner_budget_50', 'slimming_rules')"))